name: 'Save build artifacts'
description: ''
runs:
  using: "composite"
  steps:
    - name: Save build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: |
          destination/repo/*