name: 'PR[*]'

on:
  # Run workflow after pull-request
  pull_request:

jobs:

  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Run ktlint check
        uses: ./.github/actions/ktlint

  unit_tests:
    runs-on: ubuntu-latest
    needs: [ktlint]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        uses: ./.github/actions/test-unit
 
  dry_build:
    runs-on: ubuntu-latest
    needs: [ktlint, unit_tests]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Dry build
        uses: ./.github/actions/assemble

  